### ISSUE TITLE
Split request data from request and add a split method to context to make re-using context easier 

### ISSUE THREAD

**Issue by mehcode** [mehcode/shio-rs#17]
Handlers are currently of the form: `(Context) -> _`

This is logically equivalent to: `(State, Request, Data) -> _`

When reading request data, we consume the entire context.

I'd like to see the following be possible:

```rust
let (state, request, data) = context.split();
```

 - [x] Rename `Context::body` to `Context::data`
 - [x] Add `shio::Data` (replacing `shio::request::Body`)
 - [x] Extract `shio::State` out of `shio::Context`
 - [x] Add ~`Context::split`~ `Context::deconstruct`

Perhaps `split` or `Data` are the wrong words here. Suggestions welcome.

**Comment by Meralis40** [comment]
I think we shouldn't rename `Context::body` to `Context::data`, because we talk about the body of the request.
Also, I think `Context::split` should be
```rust
let (handle, state, request, body) = context.split();
```
Note the handle. Futhermore, the body is already into request, so we need to have a `Request::split()`
that split the body from the remaining (http version, uri, method & headers).

If we have to name this, I propose to follow hyper here, and use `Context::deconstruct()` instead of `Context::split()`.

**Comment by mehcode** [comment]
> I think we shouldn't rename Context::body to Context::data, because we talk about the body of the request.

The argument still works the other way: "request data" vs "request body". The former arguably being more clear to newcomers. As `Data` is a universal term to mean, well, data. On the other hand, `Body`, is a HTTP specific term that then needs further explanation.

>  Also, I think Context::split should be [...]

Good catch. I did forget about the poor handle.

> Futhermore, the body is already into request [...]

It's in the Request object currently. An example from an existing web framework, [Rocket](https://api.rocket.rs/rocket/type.Handler.html) currently separates a `Request` from its `Data`.

> If we have to name this, I propose to follow hyper here, and use Context::deconstruct() instead of Context::split().

Note that `deconstruct` is part of Hyper 0.11. Hyper 0.12 will be using [`http`](https://github.com/carllerche/http) and will have [`into_parts`](https://docs.rs/http/0.1.0/http/request/struct.Request.html#method.into_parts).

----

My current thoughts are:
 - `shio::Request` should be a wrapper around [`http::request::Parts`](https://docs.rs/http/0.1.0/http/request/struct.Parts.html)
 - `shio::Data` should be a `futures::Stream` that will wrap `hyper::Body`
 - `shio::Context` should have a `deconstruct` method that returns: `(handle, state, request, data)`. `into_parts` seems specifically named for `http`'s naming.

**Comment by Meralis40** [comment]
For naming "data" vs "body", you're right. I haven't a preference.
The rest is OK for me.
