### ISSUE TITLE
Shared global dependencies

### ISSUE THREAD

**Issue by algermissen** [mehcode/shio-rs#29]
What is your aim for adding shared dependencies (eg. metrics, logging, database handles) to handler functions? Should I provide the handlers as closures over the dependencies or do you plan to provide access to the shared data of the context?

**Comment by algermissen** [comment]
Never mind, I finally understood how to do it with an instantiated struct as in the 'stateful' example.

**Comment by mehcode** [comment]
@algermissen In the next release you will be able to provide shared state to all handlers. It is stored in a `Send + Sync` TypeMap (so 1 global value per type).

```rust
Shio::default().mange(state).run(":7878")
```

Accessible via:

```rust
context.shared().get::<State>()
```
