### ISSUE TITLE
Crates.io repository links to wrong repository

### ISSUE THREAD

**Issue by stianeklund** [mehcode/shio-rs#6]
https://crates.io/crates/shio links to https://github.com/mehcode/shio which doesn't exist.

**Comment by mehcode** [comment]
@stianeklund Thanks for the heads up. It's actually already [fixed on master](https://github.com/mehcode/shio-rs/blob/master/Cargo.toml#L6), I just haven't pushed that to https://crates.io yet. It'll get fixed when I push up `v0.0.5`.
