### ISSUE TITLE
Routing, Parameters, Syntax

### ISSUE THREAD

**Issue by mehcode** [mehcode/shio-rs#8]
Currently routing is only static matching of URLs. That's certainly not very flexible. I'm going to outline my current ideas for the router below.

### Basic

  - The leading `/` may be omitted

    ```rust
    "user"

    // same route as above
    "/user"
    ```

#### Parameters

  - Parameters are defined with `{name}` in the route pattern
  - Routes with `0` parameters are classified as "static routes" and have a
    higher weight than routes with `>= 1` parameters

    ```rust
    "user/{id}"

    // will capture exact match even if defined after "user/{id}"
    "user/profile"

    "posts/{post}/comments"
    ```

  - `{name}` is defined as `[^\/]+` by default, that is, `{name}` will match up to the next `/`

    ```rust
    // will match "/user/230" but not "/user/329/blah"
    "user/{id}"
    ```

  - A regular expression may be defined in the format `{name: pattern}`.

    ```rust
    "user/{id: [^\\/]+}"
    "static/{file: .*}"
    "articles/{year: [0-9]{4}}"
    "messages/{category: all|mine|yours}.{format: json|xml}"
    ```

  - `{..name}` is defined as shorthand for `{name: .*}`, that is, `{..name}` will match the rest of the URL

    ```rust
    "static/{..file}"
    ```

## Handler

```rust
use shio::router::Parameters;

fn user_get(ctx: Context) -> Result<Response, _> {
    // ctx.get::<_> accesses a type map
    let id_s: String = ctx.get::<Parameters>().get("id")?;
    // `Parameters::get` returns an routing mismatch error when
    // parsing fails that will cause the router
    // to look at the next route
    let id: u64 = ctx.get::<Parameters>().get("id")?;
}

fn main() {
    // [...]
    router.route((Method::Get, "/user/{id}", user_get));
    // [...]
}
```

**Comment by saggit** [comment]
looks simple and cool, what do you think about `django` style route?
like 
```
router.route((Method::Get, "^/user/(?P<id>\d+$", user_get));
```

**Comment by mehcode** [comment]
@saggit I'm not a huge fan of django's routing as its less of a route syntax and more of a "use regex here".

That said, these route patterns are just regex in the end so I'd be fine with something like the following as a way to "escape" the route syntax.

```rust
extern crate regex;
use regex::Regex;

// [...]

router.route((Method::Get, Regex::new(r"^/user/(?P<id>\d+)$"), user_get));
```

**Comment by saggit** [comment]
Yes, I agree, anyway i feel good about the current route design.

**Comment by huntiep** [comment]
I've implemented a router that works similarly to what you've outlined for my own framework. Most of it is independent of the framework, and I've been thinking of splitting it off into its own crate. Would you be interested in this? You can view the source [here](https://git.hunterpraska.com/hayaku/hayaku-path/src/master/src/trie/mod.rs), and [the tests](https://git.hunterpraska.com/hayaku/hayaku-path/src/master/src/trie/mod.rs#L272) show examples of the syntax. 

Most of your examples work with slight modifications to the route syntax, but I know that right now `"messages/{category: all|mine|yours}.{format: json|xml}"` would not work.

**Comment by mehcode** [comment]
@huntiep :wave: Neat framework. 

I'm using [`regex::RegexSet`](https://doc.rust-lang.org/regex/regex/struct.RegexSet.html) to power `shio::Router` at the moment (and performance is blazing 🐎).

I wouldn't mind switching to an external router if it can consistently beat the performance of `RegexSet`. From what I understand, `RegexSet` compiles down into a NFA which is going to be hard to beat by a manual trie.

---

If you want to chat more about contributing in other areas or anything else web-y, drop in to [#shio](https://kiwiirc.com/client/irc.mozilla.org/#shio). It'd be fun to bounce ideas around.
